### ISSUE TITLE
star already!help pls

### ISSUE THREAD

**Issue by ilovebody** [TheHudek/FandomVideoGenerator#4]
Welcome to TheHudek's FandomVideoGenerator
Traceback (most recent call last):
  File "\FandomVideoGenerator-master\main.py", line 10, in <module>
    n, length, number_of_comments, final_images = text_to_mp3()
  File "\FandomVideoGenerator-master\voices.py", line 20, in text_to_mp3
    n, final_images = get_pictures()
  File "\FandomVideoGenerator-master\fanobject.py", line 56, in get_pictures
    fanobject_chosen = fandom.page(title=os.getenv("PROMPT"))
  File "C:\Users\XXXX\AppData\Local\Programs\Python\Python38\lib\site-packages\fandom\fandom.py", line 215, in page
    return FandomPage(wiki, language, title=title, redirect=redirect, preload=preload)
  File "C:\Users\XXXX\AppData\Local\Programs\Python\Python38\lib\site-packages\fandom\FandomPage.py", line 39, in __init__
    self.__load(redirect=redirect, preload=preload)
  File "C:\Users\XXXX\AppData\Local\Programs\Python\Python38\lib\site-packages\fandom\FandomPage.py", line 77, in __load
    request = _wiki_request(query_params)
  File "C:\Users\XXXX\AppData\Local\Programs\Python\Python38\lib\site-packages\fandom\util.py", line 86, in _wiki_request
    raise RequestError(api_url, params)
fandom.error.RequestError: Your request to the url "https://daenerys_targaryen.fandom.com/en/api.php" with the paramaters "{'action': 'query', 'redirects': True, 'titles': '$P$G', 'format': 'json'}" either returned nothing or returned data in a format other than JSON. Please check your input data.

**Comment by TheHudek** [comment]
What’s your `.env`? I suspect you had `daenerys_targaryen` in the `WIKI` section.
